### ISSUE TITLE
Call to a member function getKey() on null

### ISSUE THREAD

**Issue by alblez** [404labfr/laravel-impersonate#10]
Hi

Maybe I'm missing something, the package works perfect when I do something like this:
`Auth::user()->impersonate(User::find(1));`

But when I try to use the blade directive for example:

//admin/users
> @canImpersonate
>     < a href="{{ route('impersonate', $user->id) }}" class="btn btn-xs btn-default">
>     <i class="fa fa-eye"></i> Impersonate
>     < /a>
> @endCanImpersonate

It redirect to `impersonate/take/1` and show the following error:

> FatalThrowableError in ImpersonateController.php line 32:
> Call to a member function getKey() on null

Could you please give me some advice to make the package works properly with blade directives?

**Comment by MarceauKa** [comment]
Hi!

Thank you for your feedback! Did you customize the default user or your auth guard?

**Comment by drbyte** [comment]
You said it works if you call `Auth::user()->impersonate()` directly, so that means the trait has been added.
But it's failing when hitting the `route`.  Now, I would expect it to say unknown route if you hadn't added the `Route::impersonate();` macro.  Did you do anything else with routes?


[Lines 31-32](https://github.com/404labfr/laravel-impersonate/blob/master/src/Controllers/ImpersonateController.php#L31-L32) are: 

```php
        // Cannot impersonate yourself
        if ($id == $request->user()->getKey()) {
```

It's looking for `getKey()` as a function of the object determined by `$request->user()` ... so, if that's `null` (as per the error), then:
- you're not logged in, or 
- your User guard is not standard, insomuch as a standard User object is not being returned (like it usually is) as part of the `Request` from the [Router](https://github.com/404labfr/laravel-impersonate/blob/master/src/ImpersonateServiceProvider.php#L96) 

It can't call `getKey()` because it's not finding anything to call it "on" (needs a User object with the Impersonate trait attached).

As @MarceauKa said, it's as though you've changed your app's User class, or are not using the default auth guard. Are you using some "other" authentication method?  Something other than the default Session handler?

**Comment by alblez** [comment]
Hi Marceau

I don't use the "name" field in User model, and I implement Sentinel to work with roles, authentication is driven by auth guard without customizations

This is how my "User" model looks:
```
namespace App;

use Illuminate\Notifications\Notifiable;
use Spatie\Activitylog\Traits\LogsActivity;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Cashier\Billable;

class User extends Authenticatable
{

    use Notifiable;
    use LogsActivity;
    use Billable;
    use Lab404\Impersonate\Models\Impersonate;
...
```

I additionally debug on the line where the error occurs, and I found that the variable $request returns `null`

**Comment by drbyte** [comment]
My tired eyes could be deceiving me, but I'm not sure this package is compatible with Sentinel, at least not the way its `ImpersonateController` is written, where it depends on `$request->user()` and `getKey()`.

Sentinel overrides the $request user assignment:
https://github.com/cartalyst/sentinel/blob/2.0/src/Laravel/SentinelServiceProvider.php#L426
but then doesn't implement the `getKey()` method; it does offer a `getUserId()` method though:
https://github.com/cartalyst/sentinel/blob/2.0/src/Users/UserInterface.php#L30

`ImpersonateController::take()` might need to lookup `$request->getUserResolver` and consider taking alternate actions if the default is not being used.


(I will say `laravel-impersonate` works great when the default User and Guard are in place. And operates seamlessly with `spatie/laravel-permissions` package for providing roles/permissions support.)

**Comment by MarceauKa** [comment]
@drbyte Thank you for your answers :)

**Comment by Konafets** [comment]
See #8

**Comment by MarceauKa** [comment]
Closed for inactivity.
