### ISSUE TITLE
Impact on remember_token?

### ISSUE THREAD

**Issue by drbyte** [404labfr/laravel-impersonate#11]
I've been using this package happily on a project, except that users are all complaining that their "remember me" stopped working.

My usual suspect was broken cookies, or bad remember_tokens in the user table, so I cleared all those, but the problem persists. The only other change was adding this package.

Wondering if you've seen any evidence of this same symptom, or have any ideas why it would be interfering? 

Just using the default `file` session driver. All `/config/session.php` is same as standard Laravel 5.4 release defaults.

**Comment by MarceauKa** [comment]
Hi, than you for your issue. I'm looking to it.

**Comment by MarceauKa** [comment]
Confirmed. When you leave impersonation of an user the remember_token is updated.

**Comment by MarceauKa** [comment]
This is due to the `logout()` method that's calling the method `cycleRememberToken()`.

Two scenarios to fix that:

1. Save the impersonated user `remember_token` before taking impersonation and restoring it when  leaving.

2. Creating an extension to the `SessionGuard` with a custom implementation of `login()` and `logout()`.

In both case, I'll need an update because I don't want login and logout events to be fired.

**Comment by drbyte** [comment]
Will swapping `remember_token`s prevent the actual user from logging in whilst already being impersonated on another computer?

**Comment by MarceauKa** [comment]
Fixed. See https://github.com/404labfr/laravel-impersonate/commit/c76bb96da9ca53b70fd3ce5d063722076ffcbcb4

**Comment by drbyte** [comment]
Thanks! Will upgrade and try it out!
