### ISSUE TITLE
cant impersonate more than once in multiguard setup

### ISSUE THREAD

**Issue by ctf0** [404labfr/laravel-impersonate#123]
for example lets say we have 2 guards `web, driver` & 
to activate the impersonation we use `route('impersonate', ['id' => $model->id, 'guardName' => 'driver])`

we will have 2 scenarios 
- as long as we are using `web`, everything is working as expected
- tryin to use any other guard ex.`driver` more than once will logout the user and u will be redirected to login.

not sure what is the issue 😢

**Comment by HashmatWaziri** [comment]
I have almost the same problem facing : I am using the https://github.com/Hesto/multi-auth package for multi auth and when I pass `route('impersonate', ['id' => $row->id, 'guardName' => 'employee'])`, the employee who is trying to impersonate another employee is redirected to the web guard login(mywebsite.com/login) instead of impersonating the user. By the way, I am using different models, take for example, for web I use User and for employee I use Employee Model.

**Comment by ctf0** [comment]
@HashmatWaziri i no longer have this issue, if u still have urs, plz open a new ticket.

**Comment by ctf0** [comment]
issue sadly still exists 😢 , it might work a few times b4 it fails, but surely it will.

**Comment by paramako** [comment]
Have simiral issue with multiauth. As impersonator (Admin model with admin guard and admin table) i try to impersonate several users (User model with web guard and users table) per one.
When i impersonate first user it works fine.
Than i leave impersonation and trying to impersonate second user. Quiet login method returns true but than app redirects me to web guard login page.

**Comment by ctf0** [comment]
hi again, i've made some changes to the controller & so far its working without logging me out, plz apply it manually to ur app and reply back with any findings

https://github.com/ctf0/laravel-impersonate/blob/f12f84afb9e76a209c64e6769116d79f237e52e4/src/Controllers/ImpersonateController.php

**Comment by koencg** [comment]
Same issue here - in multiguard scenario I'm taken to the login page.
