### ISSUE TITLE
Impersonate only roles/permissions without actually impersonating a user

### ISSUE THREAD

**Issue by Astalyos** [404labfr/laravel-impersonate#185]
Hi, I'm actually working on a tool to be able to impersonate a user (which is totally fine until here), and impersonating a role/permission (I will call that roleplay)

I'm using Spatie/laravel-permission.

I'm looking for a way to impersonate a role without changing the logged user
For example : 
roles : admin, manager, superadmin
I would like to stay logged as "Me" but temporally change my role 

Does anyone have an idea of how I could do this ?

**Comment by TonyPartridgeR** [comment]
You are best of having test users for that. But if you insist… you would just implement what Laravel-impersonate does but instead of changing the user you change the users roles.





Tony Partridge



Product & Development Specialist
        [cid:rielayachtstransparentpngemail_8cb896b0-8d3a-498c-9490-b6a3e8151e3d.png]



T:

+44 1624 640554

E:

***@***.******@***.***>

A:

1st Floor, 34 Hope Street, Douglas, IM1 1AP, Isle of Man

View ***@***.***,-4.4881042,649m/data=!3m2!1e3!4b1!4m6!3m5!1s0x486385141b055c57:0xfdd74b2f1e5031c3!8m2!3d54.1490313!4d-4.4859155!16s%2Fg%2F1tg_l11q> | riela-yachts.com<http://www.riela-yachts.com/>
                [cid:linkedin_4e80d1cd-f2ae-4bba-922c-1621f743bf8d.png] <https://www.linkedin.com/company/riela-yachts/>
<https://www.linkedin.com/company/riela-cyber>
        [cid:facebook_b5d67652-9acf-4c41-b172-760a3a955302.png] <https://www.facebook.com/RielaYachtsLtd>
<https://www.facebook.com/rielacyber>
        [cid:twitter_f8319272-9b60-4a93-8c83-d2c969ca8ee3.png] <https://twitter.com/RielaYachts>
<https://twitter.com/rielacyber>
        [cid:insta_de6d8856-e22c-4a8a-bbf4-1b7511154e90.png] <https://www.instagram.com/rielagroup/>
<http://www.instagram.com/rielagroup>











Riela Yachts (trading name of Riela Yachts Limited), is part of the Riela family<http://www.riela-group.com/> of companies.

This e-mail (including all attachments) is intended for the named addressee only. It is confidential and if you have received it in error, please contact us immedi­­ately and then delete it and any attachments. You should not disclose its contents to any other person and any other use or disclosure is strictly prohibited.

From: H.Gaetan ***@***.***>
Date: Thursday, 5 October 2023 at 01:06
To: 404labfr/laravel-impersonate ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [404labfr/laravel-impersonate] Impersonate only roles/permissions without actually impersonating a user (Issue #185)

Hi, I'm actually working on a tool to be able to impersonate a user (which is totally fine until here), and impersonating a role/permission (I will call that roleplay)

I'm using Spatie/laravel-permission.

I'm looking for a way to impersonate a role without changing the logged user
For example :
roles : admin, manager, superadmin
I would like to stay logged as "Me" but temporally change my role

Does anyone have an idea of how I could do this ?

**Comment by TonyPartridgeR** [comment]
You are best of having test users for that. But if you insist… you would just implement what Laravel-impersonate does but instead of changing the user you change the users roles.

**Comment by drbyte** [comment]
@Astalyos One way to do that might be to leverage Laravel's `Gate::after()` functionality. Basically, it fires after all `abilities` checks have been done, and then checks for additional changes that are needed.  A classic use-case for this is to prevent even a super-admin from editing something that "nobody" should change, or to protect a member's private data even from Admins.

In theory you could hook into that stage and when it checks for a certain ability, your custom code will check whether the "new" role should be able to do that, and grant it, and check whether your "old"/existing/usual role should be able to do it, and if not then deny it ... basically simulating the other role. Your "trigger" for it could be a simple new session variable that tracks what role/s you're suspending and which role/s you're granting for this temporary time, and probably set an expiration with it too.

**Comment by drbyte** [comment]
Laravel Daily posted a video which partially touches on this concept. Again, you'd want to store something in the session about the user's current state. 
And if your app is built on authorizing 'abilities' related to 'permissions' (instead of always only checking whether they have a certain 'role'), like I said in my post above you'll need to track what permissions you're wanting to "keep" vs "add" to the user when they've switched roles, kinda in the way I described above.

**Comment by Astalyos** [comment]
Not sure if it's the right way but, I think I've found a easier way
It has nothing to do anymore with the impersonate package but it does work

I'm storing the roles of the user in the user Db, then switch roles, and when I want to come back clear the field in the db and reattribute the right ones to the user

I'll get a look at what you sent ! 
Thank you for your help! Really appreciate
@drbyte @TonyPartridgeR
