### ISSUE TITLE
Can canImpersonate() include the user ID

### ISSUE THREAD

**Issue by llhilton** [404labfr/laravel-impersonate#29]
Is it possible to include the ID of the user to be impersonated in the canImpersonate() check? We have admins that have authority over only a subset of users, so we want to check and make sure that the user they're trying to impersonate is within their subset. I think we have found a work-around, but if this was included in the library to begin with, it would be super-nice. :)

**Comment by drbyte** [comment]
Good point.

You can override the default `canImpersonate()` call by simply re-declaring it in the same model where you've included the trait. Yours will supercede the trait.

So something like this would probably work for you:
(The trait just returns `true` automatically, by default, so this changes that behavior to suit your app.)

```diff
class User ... {
+  use Lab404\Impersonate\Models\Impersonate;

...

+    public function canImpersonate(User $toImpersonate)
+    {
+       // $this->usersICanImpersonate is a collection
+        return $this->usersICanImpersonate->contains($toImpersonate);
+    }

...
}
```
You could use an array instead of a collection, with a few changes.

**Comment by jozeflambrecht** [comment]
@llhilton Could you please share your workaround solution? I am also looking to restrict access to only users with the a same team_id ..

**Comment by llhilton** [comment]
I haven't had time to dig out the answer, but I think I ended up applying the restriction on the user to be impersonated, checked with a function like "canBeImpersonatedBy." I'll try and get into it in the next couple of days.
