### ISSUE TITLE
remember user not working

### ISSUE THREAD

**Issue by BAKTETE** [404labfr/laravel-impersonate#31]
After installing the package the remember me stopped working i doubled checked but same scenario happens

**Comment by drbyte** [comment]
Agreed. 
They made some improvements after I reported it in #11 
But the problem still persists:
- "impersonated" session will log out after it expires, regardless of Remember Token.
- after leaving impersonation, "impersonator's" session will also log out after it expires, regardless of Remember Token

**Comment by MarceauKa** [comment]
Does the tests pass in your project? ([this one](https://github.com/404labfr/laravel-impersonate/commit/c76bb96da9ca53b70fd3ce5d063722076ffcbcb4#diff-ce3578c601fa5630dd2b1df1d2b111dbR80))

**Comment by drbyte** [comment]
Upon impersonation, the `remember_web_zzzzzzzzzzzzzzzz` cookie is deleted from the browser, despite the `login_web_zzzzzzzzzzzzzz` still being present in the app's session store.

Without the `remember` cookie, when the session actually does expire, the browser can't negotiate to revive the `remember`-ed session.

The provided tests pass, but the tests don't test this factor.

**Comment by Livijn** [comment]
I'm having the same issue.

**Comment by MarceauKa** [comment]
Ok, I'll try to replicate. Any ideas?

**Comment by Livijn** [comment]
I have double checked what *drbyte* wrote, and it is true as well. I'm not sure whether you are required to delete that cookie in order to impersonate another user. I guess that is why you are deleting it, but in case it is not required – just don't delete it. 🤙

However, a naive way of solving this would be instead of deleting the cookie, you just rename it to `temp_remember_web_xxxxxxx`. Then upon "revert", you revert the name change. This would requiring always using the revert option unless we added some middleware checking for this temp cookie.

**Comment by MarceauKa** [comment]
See the [1.4](https://github.com/404labfr/laravel-impersonate/releases/tag/1.4.0)
