### ISSUE TITLE
is it possible to impesonate using laravel passport accesstoken?

### ISSUE THREAD

**Issue by codeitlikemiley** [404labfr/laravel-impersonate#36]
How can i use this package to impersonate a user, that is authenticated by laravel spark, access token?
anyone had any idea of doing it thanks

**Comment by zek** [comment]
I am developing my current project in vue using laravel as backend. 

That would be super cool if we can use impersonate with laravel passport

**Comment by MarceauKa** [comment]
Closed for inactivity.

**Comment by arunbabucode** [comment]
@codeitlikemiley Don't know if it's relevant anymore. At least, might help someone who has similar issues.

I recently had a similar requirement, where I used laravel sanctum. The app has separated backend and frontend. All the frontend items were loaded by an API call. 

What I did was extending the ImprosonateController and in the take and redirect, I explicitly deleted the token and set created a token for the new user. And then redirect to the path using `withCookie` method since I stored the token as a cookie for the user. You can use this custom route instead of the route macro.

You can extend the same logic to work with passport as well.

**Comment by sathio** [comment]
> What I did was extending the ImprosonateController and in the take and leave methods, I explicitly deleted the token and set created a token for the new user. And then redirect to the path using `withCookie` method since I stored the token as a cookie for the user. You can use this custom route instead of the route macro.

hi, can you expand a bit over this? I don't understand what you mean, thanks
