### ISSUE TITLE
[Question] Not sure where to ask, so posting here. 

### ISSUE THREAD

**Issue by rotaercz** [404labfr/laravel-impersonate#70]
First of all I think this is something I would use a lot because it's hard to debug stuff without seeing the exact circumstances of the user. I'd like to thank the dev for making this a plugin.

I have a new Laravel Project with the basic login and added this plugin.

This is probably an easy question but I'm having a hard time wrapping my head around it.

Where do you set if a person is an admin? Like, do you have to add a 'role' column to the database table or does it handle it some other way?﻿

**Comment by drbyte** [comment]
You have to do it in your app code. In the README it talks about adding a `canImpersonate` method to your User class, with an example of how it could be done. You can adapt that to check whatever other rule in your app declares a user to be an admin or otherwise be authorized to do impersonation.
https://github.com/404labfr/laravel-impersonate#defining-impersonation-authorization

**Comment by rotaercz** [comment]
Ah, I see! I understand now. Thanks for the reply!

**Comment by drbyte** [comment]
Cool. If this is resolved for you, please click the Close Issue button below.
